# Generated by Django 4.0.2 on 2022-03-26 13:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Req_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='Pending', max_length=255)),
                ('CustomerName', models.CharField(max_length=255, null=True)),
                ('GrandTotal', models.FloatField(default='0.00', null=True)),
                ('Address', models.CharField(max_length=255, null=True)),
                ('Phone', models.CharField(max_length=15, null=True)),
                ('EntryDate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Restuarant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RestuarantName', models.CharField(max_length=100, unique=True)),
                ('RestuarantCity', models.CharField(max_length=100)),
                ('RestuarantState', models.CharField(max_length=100)),
                ('RestuarantCountry', models.CharField(max_length=100)),
                ('RestuarantID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WebResources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='images/')),
                ('IDfront', models.ImageField(upload_to='images/')),
                ('IDblack', models.ImageField(upload_to='images/')),
                ('Location', models.CharField(blank=True, max_length=250)),
                ('Phone1', models.CharField(max_length=13, unique=True)),
                ('Phone2', models.CharField(blank=True, max_length=13, unique=True)),
                ('Day', models.CharField(blank=True, max_length=150)),
                ('OpeningTime', models.TimeField(blank=True)),
                ('ClosingTime', models.TimeField(blank=True)),
                ('LinkedInLink', models.CharField(blank=True, max_length=100)),
                ('GitLink', models.CharField(blank=True, max_length=100)),
                ('TwitterLink', models.CharField(blank=True, max_length=100)),
                ('FbLink', models.CharField(blank=True, max_length=100)),
                ('EntryDate', models.DateTimeField(auto_now=True)),
                ('RestuarantID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Myapp.restuarant')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Foodname', models.CharField(max_length=100)),
                ('Foodsize', models.CharField(max_length=100)),
                ('Foodprice', models.CharField(max_length=100)),
                ('Fooddescription', models.CharField(max_length=100)),
                ('Foodimage', models.ImageField(upload_to='images/')),
                ('EntryDate', models.DateTimeField(auto_now=True)),
                ('RestuarantID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Myapp.restuarant')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CustomerID', models.IntegerField(null=True)),
                ('CustomerName', models.CharField(max_length=255, null=True)),
                ('Foodname', models.CharField(max_length=150)),
                ('FoodSize', models.CharField(max_length=100)),
                ('Foodprice', models.FloatField()),
                ('Foodquantity', models.FloatField()),
                ('EntryDate', models.DateTimeField(auto_now=True)),
                ('orderID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Myapp.req_info')),
            ],
        ),
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OfferName', models.CharField(max_length=30, unique=True)),
                ('OfferItems', models.CharField(max_length=250, unique=True)),
                ('OfferPrice', models.DecimalField(decimal_places=2, max_digits=8)),
                ('OfferDescription', models.CharField(max_length=250, unique=True)),
                ('Availability', models.CharField(blank=True, max_length=10)),
                ('CreateTime', models.DateTimeField(auto_now=True)),
                ('RestuarantID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Myapp.restuarant')),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='images/')),
                ('Name', models.CharField(max_length=30)),
                ('Rank', models.CharField(max_length=50)),
                ('EntryDate', models.DateTimeField(auto_now=True)),
                ('RestuarantID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Myapp.restuarant')),
            ],
        ),
        migrations.CreateModel(
            name='Feeds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=50)),
                ('Comment', models.CharField(max_length=250)),
                ('EntryDate', models.DateTimeField(auto_now=True)),
                ('RestuarantID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Myapp.restuarant')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=30)),
                ('LastName', models.CharField(blank=True, max_length=30)),
                ('CNIC', models.CharField(blank=True, max_length=13, unique=True)),
                ('FatherName', models.CharField(max_length=30)),
                ('Age', models.IntegerField()),
                ('Gender', models.CharField(max_length=8)),
                ('EntryDate', models.DateTimeField(auto_now=True)),
                ('RestuarantID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Myapp.restuarant')),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DeliveryAddress', models.CharField(max_length=100)),
                ('ExpectedTime', models.CharField(max_length=10)),
                ('EntryDate', models.DateTimeField(auto_now=True)),
                ('CustomerOrderID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('EmployeePID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Myapp.employee')),
                ('RestuarantID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Myapp.restuarant')),
            ],
        ),
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Status', models.CharField(max_length=30)),
                ('Amount', models.CharField(max_length=100)),
                ('DateFrom', models.DateTimeField()),
                ('DateTo', models.DateTimeField()),
                ('EntryDate', models.DateTimeField(auto_now=True)),
                ('RestuarantID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Myapp.restuarant')),
            ],
        ),
    ]
