# Generated by Django 4.0.2 on 2022-05-26 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0004_req_info_orderdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webresources',
            name='Phone1',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name='webresources',
            name='Phone2',
            field=models.CharField(blank=True, max_length=13),
        ),
    ]
