# Generated by Django 4.0.2 on 2022-05-26 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0005_alter_webresources_phone1_alter_webresources_phone2'),
    ]

    operations = [
        migrations.AddField(
            model_name='restuarant',
            name='Status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved')], default='PENDING', max_length=100),
        ),
    ]
