# Generated by Django 4.0.2 on 2022-05-26 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0007_alter_webresources_closingtime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='Amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='restuarant',
            name='Status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='Pending', max_length=100),
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BankName', models.CharField(max_length=100)),
                ('AccountNumber', models.CharField(max_length=50)),
                ('CustomerName', models.CharField(max_length=50)),
                ('EntryDate', models.DateTimeField(auto_now=True)),
                ('BillingID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Myapp.billing')),
            ],
        ),
    ]
