# Generated by Django 4.0.2 on 2022-05-27 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0008_alter_billing_amount_alter_restuarant_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompletedPayments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Status', models.CharField(max_length=30)),
                ('Amount', models.FloatField()),
                ('DateFrom', models.DateTimeField()),
                ('DateTo', models.DateTimeField()),
                ('EntryDate', models.DateTimeField(auto_now=True)),
                ('RestuarantID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Myapp.restuarant')),
            ],
        ),
    ]
