# Generated by Django 4.0.2 on 2022-06-19 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0011_alter_userprofile_image_ratings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ratings',
        ),
    ]
