# Generated by Django 4.0.2 on 2022-06-19 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0013_ratings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderDetails',
        ),
    ]
