# Generated by Django 4.0.2 on 2022-06-19 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0014_delete_orderdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Foodname', models.CharField(max_length=150)),
                ('FoodSize', models.CharField(max_length=100)),
                ('Foodprice', models.FloatField()),
                ('Foodquantity', models.FloatField()),
                ('EntryDate', models.DateTimeField(auto_now=True)),
                ('FoodID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Myapp.product')),
                ('orderID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Myapp.req_info')),
            ],
        ),
    ]
