# Generated by Django 4.0.2 on 2022-06-19 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0015_orderdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='RembemberRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EntryDate', models.DateTimeField(auto_now=True)),
                ('ProductID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Myapp.product')),
                ('orderID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Myapp.req_info')),
            ],
        ),
    ]
