# Generated by Django 4.0.2 on 2022-06-19 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0016_rembemberrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='rembemberrating',
            name='Rate',
            field=models.IntegerField(default=0),
        ),
    ]
