# Generated by Django 4.0.2 on 2022-06-22 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0017_rembemberrating_rate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BankAccount',
        ),
    ]
