# Generated by Django 4.0.2 on 2022-06-22 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0018_delete_bankaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TransactionID', models.CharField(max_length=50)),
                ('BankName', models.CharField(max_length=100)),
                ('AccountNumber', models.CharField(max_length=50)),
                ('CustomerName', models.CharField(max_length=50)),
                ('EntryDate', models.DateTimeField(auto_now=True)),
                ('BillingID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Myapp.billing')),
            ],
        ),
    ]
